#! /usr/bin/env python

import pyrosetta
from gcndesign.predictor import Predictor

hoge = Predictor()

#out = hoge.make_resfile(pdb='/Users/sminami/test/pyrosetta/neo215A.pdb')
out = hoge.pred(pdb='/Users/sminami/test/pyrosetta/neo215A.pdb')
print(out)


pyrosetta.init("-ignore_unrecognized_res 1 -ex1 -ex2aro -detect_disulf 0")
scorefxn = pyrosetta.create_score_function('ref2015')



pose_in = pyrosetta.pose_from_pdb('neo215A.pdb')
pose = pose_in.clone()

